version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Result"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/tests/Result.Tests"
    schedule:
      interval: "weekly"
